### ISSUE TITLE
can not load strapdown.js

### ISSUE THREAD

**Issue by weijarz** [michfield/sublime-strapdown-preview#11]
The script referenced by preview html 
`/home/wjzhou/.config/sublime-text-3/Installed%20Packages/Strapdown%20Markdown%20Preview.sublime-package/strapdown/strapdown.js` is unaccessible from browser because this file is located in a .sublime-package file (not a dir).

**Comment by thomscode** [comment]
IMO this should be addressed in the plugin, but in the mean time the plugin has a setting to use the web version of strapdown.js and not the one provided by the plugin. If you use web hosted version you shouldn't have this problem.

**Comment by weijarz** [comment]
@thomscode how to modify the settings? I can not find the menu item under Preference > Package Settings.

**Comment by thomscode** [comment]
In this repo, look for the strapdown settings file, it will have a sublime-settings extension. Download this file and place it in your Packages/User folder (you can find this folder by opening the command palette in Sublime and selecting the Browse Packages option)

This file will be your user settings file for the strapdown plugin. From there you can open and edit it as necessary.

**Comment by weijarz** [comment]
@thomscode thank you, it works.
